install.packages(c("colorspace", "dendsort", "pheatmap", "tidyverse", "RColorBrewer", "argparse", "proto", "findpython", "getopt", "jsonlite", "knitr"), dependencies=TRUE)
source("https://bioconductor.org/biocLite.R")
biocLite() 
#biocLite("rtracklayer")
#library(rtracklayer)
#biocLite(c("edgeR", "limma", "scran", "GSEABase", "GSVA", "ReactomePA", "clusterProfiler", "genefilter", "maftools", "org.Hs.eg.db"))
#biocLite(c("COMBINE-lab/wasabi", "geneplotter", "pachterlab/sleuth", "DOSE", "DESeq2", "scater", "biomaRt", "ChIPseeker", "GenomicFeatures", "AnnotationDbi"))
#install.packages("reticulate")
#library(reticulate)
#conda_install("env", "python=3.6")

#install.packages(c("dendsort", "argparse"), dependencies=TRUE)

#library(colorspace)
#library(dendsort)
#library(pheatmap)
#library(tidyverse)
#library(RColorBrewer)  
#library(argparse)
#library('proto')
#library('findpython')
#library('getopt')
#library('jsonlite')
